version: "3.9"

services:
  hole-frontend:
    build:
      context: .
      dockerfile: Dockerfile # 确保 Dockerfile 的路径正确
    container_name: thu-hole-frontend-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always



